added Gitgub Reusable templates

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -41,12 +41,30 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Extract version from release branch
+      - name: Read version
         id: getversion
         run: |
-          BRANCH="${GITHUB_REF_NAME}"   # release/1.2.3
-          VERSION="${BRANCH#release/}"
-          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
+          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
+
+          echo "Current branch: $BRANCH_NAME"
+
+          if [[ "$BRANCH_NAME" == release/* ]]; then
+            # Extract version from release branch name
+            VERSION="${BRANCH_NAME#release/}"
+            VERSION="${VERSION#v}"   # strip leading v if present
+            echo "Detected release branch. Version: $VERSION"
+          else
+            # Extract version from Helm chart
+            VERSION=$(awk -F'"' '/^appVersion:/ {print $2}' "${{ inputs.chart_path }}")
+            echo "Detected non-release branch. Version from chart: $VERSION"
+          fi
+
+          if [ -z "$VERSION" ]; then
+            echo "ERROR: Version could not be determined"
+            exit 1
+          fi
+
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
       - name: Google Auth (WIF)
         id: auth
@@ -73,3 +91,13 @@ jobs:
           IMAGE="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_NAME}/${VERSION}"
           docker build -t "${IMAGE}:${GITHUB_SHA}" -t "${IMAGE}:latest" ${{ inputs.build_args }} ./
           docker push --all-tags '${{ env.GAR_LOCATION }}'-docker.pkg.dev/'${{ env.PROJECT_ID }}'/'${{ env.GAR_NAME }}'/${{ steps.getversion.outputs.version }}
+
+      - name: Run Notification
+        id: runnotificationsent
+        uses: act10ns/slack@v1
+        with:
+          status: ${{ job.status }}
+          steps: ${{ toJson(steps) }}
+          channel: ${{ secrets.SLACK_CHANNEL }}
+          message: Running release build on {{ env.GITHUB_REF_NAME }} branch ${{ job.status }}
+        if: always()
